### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by hpatoio** [dunglas/DunglasTodoMVCBundle#2]
Would be nice see how to handle validation. For instance  not allow `ToDo` with `title` with less then 4 characters.

**Comment by dunglas** [comment]
Hi @hpatoio,

Validation is already handled. For instance a title cannot be blank.

See https://github.com/dunglas/DunglasTodoMVCBundle/blob/master/Entity/Todo.php and https://github.com/dunglas/DunglasTodoMVCBundle/blob/master/Controller/TodoController.php#L59.
